function main(): int {
    let failCounter: int = 0;
    let testResult: int = 0;
    {% for test_name, test_data in item.method_test_index_data.items() %}
    {%- if item.method_expected_exception is defined %}
    testResult = checkTestResult({{.item.method_name}}{{.test_name|capitalize}}())
    {%- else %}
    let expectedData{{.test_name|capitalize}} : {{.item.result_type}} = {{.item.method_expected_data[test_name]}}
    testResult = checkTestResult({{.item.method_name}}{{.test_name|capitalize}}(), expectedData{{.test_name|capitalize}})
    {%- endif %}
    printTestVerdict(testResult, "{{.test_name}}")
    failCounter += testResult
    {% endfor %}
    if (failCounter > 0) return 1
    return 0;
}

function printTestVerdict(flag: int, testName: String) {
    if (flag == 0) {
      console.println(testName + " : PASSED")
    } else {
      console.println(testName + " : FAILED")
    }
}
